version: 0.0
os: linux
files:
  - source: start.sh
    destination: /home/ec2-user
  - source: docker-compose.yml
    destination: /home/ec2-user

# permissions:
#   - object: /home/ec2-user/script.sh
#     mode: 777
#     owner: ec2-user
#     type:
#       - file
#   - object: /home/ec2-user/docker-compose.yml
#     mode: 777
#     owner: ec2-user
#     type:
#       - file

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ec2-user