version: 0.2

env:
  variables:
    DOCKER_USERNAME: "imriteek"

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - cd frontend/
      - npm install 
      - npm run build

      - cd ../backend/
      - docker build -t imriteek/backend:$CODEBUILD_BUILD_NUMBER .
      - docker tag imriteek/backend:$CODEBUILD_BUILD_NUMBER imriteek/backend:latest
      - docker images
      - docker push imriteek/backend:$CODEBUILD_BUILD_NUMBER
      - docker push imriteek/backend:latest

      - cd ../admin/
      - npm install 
      - npm run build
      
artifacts:
  files:
    - appspec.yml
    - docker-compose.yml
    - start.sh
  discard-paths: yes

secondary-artifacts:
  admin_artifacts:
    base-directory: admin/dist
    files:
      - '**/*'
    name: admin_artifacts
    discard-paths: no

  frontend_artifacts:
    base-directory: frontend/dist
    files:
      - '**/*'
    name: frontend_artifacts
    discard-paths: no
